code migration
zxsecurity/steamer pull request #13
Opened 2021-01-12 23:12 UTC by mlr0p

This PR implements modular parsing to reduce code reduce, and also migrates the old code to the new template #11 .

2021-01-13 23:27 UTC, SoftPoison requested changes
Good work overall, couple of small comments here and there but nothing major :)

2021-01-13 23:27 UTC, SoftPoison commented on importers/util/common.go
> +	fileNamePtr := flag.String("i", defaultFileName, "Path to dump file")
as you're dereferencing the fileNamePtr anyway, might as well just change this to `fileName := *flag.String(...)`

2021-01-13 23:27 UTC, SoftPoison commented on importers/util/custom-parse.go
> +func ParseSQL(line string, table string) ([]string, error) {
This should be fine for now, but I'm not sure if this is the most resilient parser

2021-01-13 23:27 UTC, SoftPoison commented on importers/forbes.go
> +/***
Is this comment meant to be here?

2021-01-13 23:27 UTC, SoftPoison commented on importers/util/common.go
> +// Package util provides common code for all the importers
Since we're using GenericData for almost everything, perhaps we move the struct in here?

2021-01-14 02:16 UTC, mlr0p commented on importers/forbes.go
> +/***
oh no...

2021-01-14 02:17 UTC, mlr0p commented on importers/util/custom-parse.go
> +func ParseSQL(line string, table string) ([]string, error) {
will keep an eye out for this in the future then, all others are fixed, hopefully

2021-01-14 22:02 UTC, SoftPoison approved these changes
LGTM

2021-01-27 05:50 UTC, ss23 approved these changes
LGTM 👍

2021-01-28 20:43 UTC, merged