Official driver
zxsecurity/steamer pull request #20
Opened 2023-09-26 22:05 UTC by cicada-legs

updated old mgo driver to new mongo-driver

2023-10-25 00:05 UTC, SoftPoison requested changes
Looks pretty good! Just a couple of small changes and then it should be good to go.

It may also be worth seeing if you actually need the `Id` field for the data structures, or whether it can be removed entirely with the new driver. But only if you have the time to do it :^)

2023-10-25 00:05 UTC, SoftPoison commented on go.mod
>  	gopkg.in/mgo.v2 v2.0.0-20190816093944-a6b53ec6cb22
don't forget to remove the old driver from the dependencies!

2023-10-25 00:05 UTC, SoftPoison commented on importers/houzz.go
> +	fmt.Println("check in houzz parse: ", entries)
is this a leftover debug println? if so, please remove it :)

2023-10-25 00:05 UTC, SoftPoison commented on importers/linkedin2016-hashes.go
> +func importLine(threader <-chan string, mgoreal *mongo.Client, doner chan<- bool, ctx context.Context) {
probably worth renaming `mgoreal` to `client` here.

great idea with passing in the context as a parameter btw! makes it a *lot* easier to add contexts with timeouts/deadlines later

2023-10-25 00:05 UTC, SoftPoison commented on importers/util/common.go
> +	mongo      *mongo.Client
worth renaming `mongo` to `client` (or `dbClient` even) here

2023-10-25 00:05 UTC, SoftPoison commented on importers/util/common.go
>  		fmt.Fprintf(os.Stderr, "Error opening file\r\n")
`fmt.Println` outputs to stdout instead of stderr. It would be better to do something like:

```go
fmt.Fprintf(os.Sttderr, "Error opening file: %v (path: %s, file: %s)\n", err, os.Getwd(), i.fileName);
```

2023-10-27 03:36 UTC, cicada-legs commented
ty! i think the Id field is used a few times in index.html for knowing when to print a new row so i've kept it as is for now.  all other issues have been resolved :D

2023-11-01 20:58 UTC, SoftPoison approved these changes
Looks good! Well done :^)

2023-11-01 20:59 UTC, merged